### ISSUE TITLE
The 'direction' property must not be included in an EPUB Style Sheet.

### ISSUE THREAD

**Issue by sh0ji** [seefour/nest#11]
PhotoSwipe Default UI uses the `direction` CSS property, which throws an error in epubcheck. Specifically, it uses it in the [loading indicator](http://codepen.io/dimsemenov/pen/yyBWoR).
```css
.pswp__preloader {
  width: 44px;
  height: 44px;
  position: absolute;
  top: 0;
  left: 50%;
  margin-left: -22px;
  opacity: 0;
  -webkit-transition: opacity 0.25s ease-out;
  transition: opacity 0.25s ease-out;
  will-change: opacity;
  direction: ltr;
}
```
